POST http://localhost:3001/api/notes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwOWQ1NjVkMDU1NWZiMGQyNTRmMjAwZCIsInVzZXJuYW1lIjoiTHVpc2ZsbTAwIiwiaWF0IjoxNjIwOTQ2ODI4LCJleHAiOjE2MjE1NTE2Mjh9.pxoQLODCCe0p2jI7wZux1gkp8R0o7iKd4WHdw82ZUFo

{
    "content" : "created note use userExtractor" ,
    "important" : true
}

###
POST http://localhost:3001/notes
Content-Type: application/json

{
    "content" : "Note for remmember " ,
    "important" : true ,
    "creator" : {
            "name" : "Juand Diego" ,
            "LastName" : "Lopez Medina" ,
            "age" : 10
        }
}
