POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content" : "note with property creator" ,
    "important" : true ,
    "userId" : "606e31dffd6e072c9d94bbaf"
}

###
POST http://localhost:3001/notes
Content-Type: application/json

{
    "content" : "Note for remmember " ,
    "important" : true ,
    "creator" : {
            "name" : "Juand Diego" ,
            "LastName" : "Lopez Medina" ,
            "age" : 10
        }
}
